# Generated by Django 4.2.16 on 2024-12-09 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=100)),
                ('broadcast_day', models.ManyToManyField(to='broadcast.broadcastday')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broadcast.channel')),
            ],
        ),
    ]
