# Generated by Django 4.2.16 on 2024-12-11 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broadcast', '0002_broadcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceSampleSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_type', models.CharField(max_length=40, unique=True)),
                ('sample_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings_type', models.CharField(max_length=40, unique=True)),
                ('ratings', models.FloatField()),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broadcast.broadcast')),
            ],
        ),
    ]
