# Generated by Django 5.1.1 on 2024-12-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast_ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastratings',
            name='month',
            field=models.CharField(default='', max_length=100),
        ),
    ]
