# Generated by Django 5.1.1 on 2024-12-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast_ratings', '0003_alter_broadcastratings_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastratings',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
