# Generated by Django 5.1.1 on 2024-12-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast_ratings', '0005_alter_broadcastratings_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastratings',
            name='month',
            field=models.CharField(max_length=7),
        ),
    ]
