# Generated by Django 5.1.1 on 2024-12-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast_ratings', '0006_alter_broadcastratings_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiencesamplesize',
            name='audience_type',
            field=models.CharField(max_length=40),
        ),
    ]
