# Generated by Django 5.1.1 on 2024-12-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast_ratings', '0008_alter_broadcastratings_ratings_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiencesamplesize',
            name='audience_type',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='broadcastratings',
            name='ratings_type',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
